[package]
name = "sample"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]

[dependencies]
bitcask-rs = { path = "../.." }
actix-web = "0.6"
actix = "0.5"
failure = "0.1.1"
futures = "0.1.3"
serde = "*"
serde_derive = "*"
