[package]
name = "sample"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]

[dependencies]
bitcask-rs = { path = "../.." }
actix-web = "0.7.2"
actix = "0.7.3"
failure = "0.1.1"
futures = "0.1.23"
serde = "1.0.70"
serde_derive = "1.0.70"
